# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nick Donald's github site
email: nickjdonald@gmail.com
description:
url: "https://nickd0.github.io"
twitter_username: _nick_donald
github_username:  nickd0

img_cdn: "https://s3.amazonaws.com/nickd0.github.io"
resume_vs: v5



# Build settings
markdown: kramdown
# theme: nickd0-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: nickd0/nickd0-theme@main
# theme: nickd0-theme

sass:
  sass_dir: _sass
  style: compressed

permalink: /posts/:title

# defaults:
#   -
#     scope:
#       type: posts
#       path: _posts
#     values:
#       is_post: true
#       layout: post
#       permalink: /blog/:title

include: [_pages]
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
